name: Bump Package Version
on:
  workflow_call:
    inputs:
      type:
        required: false
        type: string
        default: patch
      package:
        required: true
        type: string

jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Version Bump
        run: yarn workspace @dannywrayuk/${{ inputs.package }} version --${{ inputs.type || 'patch'}}

      - name: Store New Version
        run: echo "NEW_VERSION=$(node -p "require('./packages/${{ inputs.package }}/package.json').version")" >> $GITHUB_ENV

      - name: Add Git Tag
        run: |
          git tag "${{ inputs.package }}v"
          git add .
          git commit -m "🚀 Release ${{ inputs.package }} v${{ env.NEW_VERSION }}"

      - name: Push Bump
        run: git pull --rebase && git push && git push --tags

      # Action is deprecated
      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ inputs.package }}-v${{ env.NEW_VERSION }}
      #     release_name: Release ${{ inputs.package }} v${{ env.NEW_VERSION }}
