name: deploy-describe-shape
on:
  push:
    branches: main
    paths:
      - packages/describe-shape
      - .github/workflows/deploy-describe-shape.yaml

  workflow_dispatch:
    inputs:
      type:
        description: Version Bump
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
defaults:
  run:
    working-directory: packages/describe-shape

jobs:
  bump-version:
    name: Bump Version
    uses: ./.github/workflows/bump-version.yaml
    secrets: inherit
    with:
      package: describe-shape
      type: ${{ inputs.type }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v3
      - run: yarn

      - name: Build
        run: yarn build

      # - name: Publish
      #   run: yarn publish --access public
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
