name: deploy-casing
on:
  push:
    branches: main
    paths:
      - packages/casing/**

  workflow_dispatch:
    inputs:
      type:
        description: Version Bump
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
defaults:
  run:
    working-directory: packages/casing

jobs:
  bump-version:
    name: Bump Version
    uses: ./.github/workflows/bump-version.yaml
    secrets: inherit
    with:
      package: casing
      type: ${{ inputs.type }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - run: yarn

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
