name: Generate Root README
on:
  push:
    branches:
      - main

jobs:
  check-cache:
    runs-on: ubuntu-latest
    outputs:
      packageData: ${{ steps.get-package-data.outputs.packageData }}
      cacheResult: ${{ steps.compare-with-cache.outputs.cache }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Get Package Data
        id: get-package-data
        run: >
          for package in $(ls packages); do
            echo \'--name="$package" --description="$(cat packages/$package/package.json | jq ".description")"\' >> PACKAGE_DATA
          done;
          echo packageData=$(cat PACKAGE_DATA | paste -sd' ' - ) >>  $GITHUB_OUTPUT

      - name: Compare With Cache
        id: compare-with-cache
        run: >
          if [[  $(echo -n ${{ steps.get-package-data.outputs.packageData }} | sha256sum) == $(cat internal/readme-generation/PACKAGE_DATA_CACHE) ]]; then
            echo "cache=hit" >> $GITHUB_OUTPUT
          else
            echo "cache=miss" >> $GITHUB_OUTPUT
          fi

  generate-root-readme:
    needs: check-cache
    runs-on: ubuntu-latest
    if: needs.check-cache.outputs.cacheResult == 'miss'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Yarn
        run: yarn

      - name: Generate Package Content
        run: >
          for packageEntry in ${{ needs.check-cache.outputs.packageData }}; do
            yarn cookie-cutter templates/root-readme-package-entry . --accept-warning=true $packageEntry
          done;

      - name: Generate README
        run: >
          for section in $(ls | grep 'ROOT_CONTENT'); do
            cat $section >> PACKAGES_SECTION
          done;
          yarn cookie-cutter templates/root-readme . --packagesSectionPath=PACKAGES_SECTION

      - name: Update Cache
        run: echo -n ${{ needs.check-cache.outputs.packageData }} | sha256sum > internal/readme-generation/PACKAGE_DATA_CACHE

      - name: Push Changes
        run: >
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md internal/readme-generation/PACKAGE_DATA_CACHE
          git commit -m "📚 README updated (automated)"
