name: Package Pull Request Checks
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - packages/**
      - .github/workflows/package-pull-request-checks.yaml
      - .github/workflows/get-changed-packages.yaml
      - .github/actions/diffToPackageArray.js
      - .github/workflows/quality-checks.yaml

jobs:
  get-changed-packages:
    uses: ./.github/workflows/get-changed-packages.yaml
    secrets: inherit

  quality-checks:
    needs: get-changed-packages
    if: fromJson(needs.get-changed-packages.outputs.packageArray) != 'null'
    strategy:
      matrix:
        package: ${{fromJson(needs.get-changed-packages.outputs.packageArray)}}
    uses: ./.github/workflows/quality-checks.yaml
    secrets: inherit
    with:
      package: ${{ matrix.package }}
