name: pr-casing
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - packages/casing/**
      - .github/workflows/pr-casing.yaml
defaults:
  run:
    working-directory: packages/casing

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Unit Test
        run: yarn test
