name: pr-describe-shape
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - packages/describe-shape
      - .github/workflows/pr-describe-shape.yaml
defaults:
  run:
    working-directory: packages/describe-shape

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Unit Test
        run: yarn test

  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v2
        with:
          dry-run: true
          strategy: upgrade
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/describe-shape/package.json
