name: pull-request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  get-changed-packages:
    uses: ./.github/workflows/get-changed-packages.yaml
    secrets: inherit

  test-matrix:
    needs: test
    strategy:
      matrix:
        package: ${{fromJson(needs.test.outputs.packageArray)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install project dependencies
        run: yarn
      - run: echo ${{ matrix.package }}
      - run: yarn workspace @dannywrayuk/${{ matrix.package }} lint
      - run: yarn workspace @dannywrayuk/${{ matrix.package }} test
      - run: yarn workspace @dannywrayuk/${{ matrix.package }} build
