name: pull-request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      packageArray: ${{ steps.changed-packages.outputs.packageArray }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: git-diff
        run: echo "filesChanged=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tr '\n' ','| sed 's/,$//')" >> $GITHUB_OUTPUT

      - id: changed-packages
        run: echo "packageArray=$(node .github/actions/diffToPackageList \"${{ steps.git-diff.outputs.filesChanged }}\")"  >> $GITHUB_OUTPUT
  test-matrix:
    needs: test
    strategy:
      matrix:
        package: ${{fromJson(needs.test.outputs.packageArray)}}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.package }}
