name: pull-request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: git-diff
        run: echo "files_changed=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}| tr '\n' ',')" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.git-diff.outputs.files_changed }}"
