name: pull-request
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git diff --name-only ${{ github.event.pull_request.base }} ${{ github.event.pull_request.head }}
